### ISSUE TITLE
数组越界

### ISSUE THREAD

**Issue by shezhi** [Res2Net/Res2Net-PretrainedModels#57]
Traceback (most recent call last):
  File "train.py", line 160, in <module>
    main()
  File "train.py", line 66, in main
    train(train_loader, model, optimizer, epoch)
  File "train.py", line 94, in train
    output = model(image)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Revisiting_Single_Depth_Estimation-master/models/net.py", line 28, in forward
    x_block1, x_block2, x_block3, x_block4 = self.E(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Revisiting_Single_Depth_Estimation-master/models/modules.py", line 62, in forward
    x_block1 = self.layer1(x)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 67, in forward
    input = module(input)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Revisiting_Single_Depth_Estimation-master/models/resnet.py", line 162, in forward
    sp = self.relu(self.bns[i](sp))
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.py", line 101, in __getitem__
    raise IndexError('index {} is out of range'.format(idx))
IndexError: index 2 is out of range

**Comment by shezhi** [comment]
我把resnet50中bottleblock替换成bottle2block，然后运行过后出现这种错误，请问什么原因呢？

**Comment by gasvn** [comment]
https://github.com/Res2Net/Res2Net-PretrainedModels/blob/master/res2net_v1b.py
你可以直接参照我们的代码。我们的代码也是根据resnet50改的。从你给的信息我无法判断出来，一般原因可能是参数没传对。

**Comment by shezhi** [comment]
好的，我试试

**Comment by shezhi** [comment]
width = int(math.floor(planes * (baseWidth/64.0)))您好，这一行代码我一直没太弄明白，请问有人知道么

**Comment by gasvn** [comment]
> 
这只是为了方便跟resnet对齐参数量写的一行代码。

**Comment by gasvn** [comment]
> width = int(math.floor(planes * (baseWidth/64.0)))您好，这一行代码我一直没太弄明白，请问有人知道么

这只是为了方便跟resnet对齐参数量写的一行代码。

**Comment by shezhi** [comment]
已收到！
